image: ubuntu

variables:
    DEBIAN_FRONTEND: noninteractive
    URL_GRASSGIS_MANUALS: 'https://grass.osgeo.org/grass74/manuals'
    TEMPORARY_LOCATION: 'temporary_location'
    DOCS_HTML_DIRECTORY: '/usr/lib/grass74/docs/html/'
    EXTENSION_PREFIX: 'build'

pages:
  script:

  # repository's $CI_PROJECT_NAME expectedly identical to the module's name

  # insall dependencies
  - apt-get update -qq && apt-get install -y -qq grass grass-dev grass-doc wget

  # some files are not installed properly, get them online
  - wget ${URL_GRASSGIS_MANUALS}/grass_logo.png
    -P $DOCS_HTML_DIRECTORY
  - wget ${URL_GRASSGIS_MANUALS}/grassdocs.css
    -P $DOCS_HTML_DIRECTORY

  # create a temporary location (needed for v<7.6)
  - grass -c EPSG:4326 ${TEMPORARY_LOCATION} -e

  # compile using g.extension from current directory to build directory
  - grass ${TEMPORARY_LOCATION}/PERMANENT --exec
    g.extension --verbose
    extension=${CI_PROJECT_NAME}
    url=.
    prefix=${EXTENSION_PREFIX}

  # copy html doc in 'public' > used conventionally for published web pages
  - cp -r ${EXTENSION_PREFIX}/docs/html public

  # create a page after the repository|module's name
  - cp public/${CI_PROJECT_NAME}.html public/index.html

  artifacts:
    paths:
    # mark the directory for preservation
    - public

  only:
  - master
